# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Clone the GitHub Repo on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install program dependacies
      run: npm install
    - name: Start the App
      run: npm run start &

    - name: Run integration tests and save output
      run: npm run test | tee test-output.log

    - name: Upload test output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-output.log

    # - name: Run integration tests
    #   run: npm run test
